version: '3'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=jobtest
    volumes:
      - dbdata:/var/lib/mysql
      - ./logs:/var/logs
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  jobtest:
    depends_on:
      - db
    image: wordpress:5.8.0-fpm-alpine
    container_name: jobtest
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=jobtest
    volumes:
      - jobtest:/var/www/html
      - ./logs:/var/logs
    networks:
      - app-network
  
  webserver:
    depends_on:
      - jobtest
    image: nginx:1.15.12-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - jobtest:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - ./logs:/var/logs
    networks:
      - app-network
  
  certbot:
    depends_on:
      - webserver
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - jobtest:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email $EMAIL --agree-tos --no-eff-email --staging -d jobtest.luxnet.ua

volumes:
  certbot-etc:
  jobtest:
  dbdata:
  ./logs:

networks:
  app-network:
    driver: bridge